version: '3.8'

services:
  web-service:
    build:
      context: ./web-service
    container_name: bhanu-bcd26-web-service
    image: bhanureddy1973/todo-app-frontend:latest
    ports:
      - "8083:3000"  # Host:Container (Access frontend on host port 8083)
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - worker-service
    restart: unless-stopped

  worker-service:
    build:
      context: ./worker-service
    container_name: bhanu-bcd26-worker-service
    image: bhanureddy1973/todo-app-backend:latest
    ports:
      - "4001:4001"  # Host:Container (Access backend on host port 4001)
    environment:
      - MONGO_URI=mongodb://mongo:27017/todo_db
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    image: mongo
    container_name: bhanu-bcd26-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

volumes:
  mongo_data:
