version: '3.8'

services:
  web-service:
    build:
      context: ./frontend
    container_name: bhanu-bcd26-web-service
    ports:
      - "8083:3000"
    depends_on:
      - worker-service
    environment:
      - REACT_APP_API_URL=http://worker-service:5000

  worker-service:
    build:
      context: ./backend
    container_name: bhanu-bcd26-worker-service
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/todo

  mongo:
    image: mongo
    container_name: bhanu-bcd26-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
